In [4]:
'''
This is the data processing script for POP909:A Pop song Dataset for Music Arrangement Generation
============
It will allow you to quickly process the POP909 Files (Midi) into the Google Magenta's music representation 
    as like [Music Transformer](https://magenta.tensorflow.org/music-transformer) 
            [Performance RNN](https://magenta.tensorflow.org/performance-rnn).

'''
import pickle
import os
import sys
import utils
from processor import MidiEventProcessor
import pretty_midi as pyd
import numpy as np



In [5]:
total = 0
def preprocess_midi(path):
    global total
    data = pyd.PrettyMIDI(path)
    main_notes = []
    acc_notes = []
    for ins in data.instruments:
        acc_notes.extend(ins.notes)
    for i in range(len(main_notes)):
        main_notes[i].start = round(main_notes[i].start,2)
        main_notes[i].end = round(main_notes[i].end,2)
    for i in range(len(acc_notes)):
        acc_notes[i].start = round(acc_notes[i].start,2)
        acc_notes[i].end = round(acc_notes[i].end,2)
    main_notes.sort(key = lambda x:x.start)
    acc_notes.sort(key = lambda x:x.start)
    mpr = MidiEventProcessor()
    repr_seq = mpr.encode([main_notes, acc_notes])
    total += len(repr_seq)
    return repr_seq

def preprocess_pop909(midi_root, save_dir):
    save_py = []
    midi_paths = [d for d in os.listdir(midi_root)]
    i = 0
    out_fmt = '{}-{}.data'
    for path in midi_paths:
        print(' ', end='[{}]'.format(path), flush=True)
        filename = midi_root + path
        try:
            data = preprocess_midi(filename)
        except KeyboardInterrupt:
            print(' Abort')
            return
        except EOFError:
            print('EOF Error')
            return
        save_py.append(data)
    save_py = np.array(save_py)
    print(save_py.size)
    np.save("pop909-event-token.npy", save_py)
            
    
# replace the folder with your POP909 data folder

 [001]

FileNotFoundError: [Errno 2] No such file or directory: '../pop909001'

In [80]:
test = pyd.PrettyMIDI("../DontStopTheParty.mid")
test3 = pyd.PrettyMIDI("../IGotAFeeling.mid")

In [9]:
preprocess_pop909("../POP909/","midi_data/")

 [001]

PermissionError: [Errno 13] Permission denied: '../POP909/001'

In [22]:
test.get_pitch_class_histogram()

array([0.23324554, 0.        , 0.07316359, 0.2405619 , 0.        ,
       0.18964004, 0.        , 0.15744805, 0.02809482, 0.        ,
       0.06321335, 0.01463272])

In [25]:
test2 = pyd.PrettyMIDI("../POP909/001/001.mid")

In [30]:
test2

In [40]:
res=[]
for note in test.instruments[0].notes:
    res.append(note.end-note.start)

In [56]:
test.instruments

[Instrument(program=25, is_drum=True, name="the party"),
 Instrument(program=51, is_drum=False, name="the party"),
 Instrument(program=84, is_drum=False, name="the party"),
 Instrument(program=119, is_drum=False, name="the party"),
 Instrument(program=33, is_drum=False, name="the party"),
 Instrument(program=81, is_drum=False, name="the party"),
 Instrument(program=36, is_drum=False, name="the party"),
 Instrument(program=80, is_drum=False, name="the party"),
 Instrument(program=87, is_drum=False, name="the party"),
 Instrument(program=100, is_drum=False, name="the party")]

In [58]:
compil_instr = pyd.Instrument(0)

In [60]:
for ins in test.instruments:
    compil_instr.notes = compil_instr.notes + ins.notes

In [65]:
len(compil_instr.notes)

5897

In [89]:
output_test = pyd.PrettyMIDI()

In [90]:
for i,ins in enumerate(test3.instruments):
    ins.name = str(i)
    output_test.instruments = output_test.instruments + [ins]

In [74]:
output_test.instruments = [compil_instr]

In [91]:
output_test.instruments

[Instrument(program=29, is_drum=False, name="0"),
 Instrument(program=49, is_drum=False, name="1"),
 Instrument(program=48, is_drum=False, name="2"),
 Instrument(program=73, is_drum=False, name="3"),
 Instrument(program=0, is_drum=True, name="4"),
 Instrument(program=81, is_drum=False, name="5")]

In [93]:
test3.get_tempo_changes()

(array([0.]), array([130.00041167]))

In [92]:
output_test.write("test.mid")

In [81]:
sum =0
for ins in test3.instruments:
    print(len(ins.notes))
    sum+=len(ins.notes)
sum

1451
723
784
682
921
384


4945

In [78]:
sum*2

11794

In [108]:
test3.get_tempo_changes()[1][0]

130.00041166797027

In [119]:
res=[]
for i in range(len(test3.instruments[0].notes)):
    res.append((test3.instruments[0].notes[i].end)/60*test3.get_tempo_changes()[1][0])

In [121]:
np.unique((res)-np.floor(res))

array([0. , 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1. ,
       1. , 1. ])

In [115]:
(np.unique(res)/60)*test3.get_tempo_changes()[1][0]

array([0.04231784, 0.12695353, 0.16927137, 0.25390705, 0.33854274,
       0.50781411])

In [3]:
np.max(np.loadtxt("../../Encoded_data/bruno mars/RunawayBaby.csv"))

1.0

In [5]:
pyd.PrettyMIDI("../../Data/bruno mars/RunawayBaby.mid")

c:\Users\Vianey Darsel\AppData\Local\Programs\Python\Python39\lib\site-packages\pretty_midi\pretty_midi.py:100: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  warnings.warn(
